name: Build and Release

on: 
  push:
    tags:
    - '*'

jobs:
  build-and-release:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Nix
        uses: cachix/install-nix-action@v20

      - name: Build
        run: |
          if [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            nix build .#packages.x86_64-darwin.default --accept-flake-config
          else
            nix build .#packages.x86_64-linux.default --accept-flake-config
          fi

      - name: Create Release and Upload Release Assets
        uses: ncipollo/release-action@v1
        with:
          artifacts: "result/bin/*"
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
