name: Build and Release

on: 
  push:
    tags:
    - '*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Nix
        uses: cachix/install-nix-action@v20

      - name: Build
        run: nix build .#packages.x86_64-linux.default --accept-flake-config
          
      - name: Create Release and Upload Release Assets
        uses: ncipollo/release-action@v1
        with:
          artifacts: ./result/bin/foliage
